version: '3'

services: 
  nginx:
    container_name: nginx-app-node
    build: 
      context: ./nginx
    image: fabiocoliveira/nginx-app-node:latest
    tty: true
    networks: 
      - node-network        
    ports: 
      - "8080:80"    
    depends_on: 
      - app
  app:
    container_name: app-node
    build: 
      context: ./node
    image: fabiocoliveira/app-node:latest    
    entrypoint: dockerize -wait tcp://db:3306 -timeout 3000s -wait-retry-interval 5s npm run prod        
    tty: true            
    networks:
      - node-network
    depends_on: 
      - db
  db:
    container_name: db
    build: 
      context: ./mysql
    image: fabiocoliveira/mysql-app-node    
    restart: always
    tty: true
    volumes: 
      - ./mysql/data_mysql:/var/lib/mysql      
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root 
    networks: 
      - node-network
    ports: 
      - "3306:3306"
networks: 
  node-network:
    driver: bridge 